import Link from "next/link";
import styles from "./homepage.module.css";

export default function Home() {
  return (
    <div>
      <Link href="/"> 
      
      <h1>Lorem ipsum dolor </h1>

      Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati magni tenetur delectus fuga corporis quibusdam natus omnis assumenda eius excepturi, et ad voluptates animi quasi iure fugit harum id odio?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati magni tenetur delectus fuga corporis quibusdam natus omnis assumenda eius excepturi, et ad voluptates animi quasi iure fugit harum id odio?   Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati magni tenetur delectus fuga corporis quibusdam natus omnis assumenda eius excepturi, et ad voluptates animi quasi iure fugit harum id odio?   Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati magni tenetur delectus fuga corporis quibusdam natus omnis assumenda eius excepturi, et ad voluptates animi quasi iure fugit harum id odio?   Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati magni tenetur delectus fuga corporis quibusdam natus omnis assumenda eius excepturi, et ad voluptates animi quasi iure fugit harum id odio?   Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati magni tenetur delectus fuga corporis quibusdam natus omnis assumenda eius excepturi, et ad voluptates animi quasi iure fugit harum id odio?   Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati magni tenetur delectus fuga corporis quibusdam natus omnis assumenda eius excepturi, et ad voluptates animi quasi iure fugit harum id odio?   Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati magni tenetur delectus fuga corporis quibusdam natus omnis assumenda eius excepturi, et ad voluptates animi quasi iure fugit harum id odio?   Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati magni tenetur delectus fuga corporis quibusdam natus omnis assumenda eius excepturi, et ad voluptates animi quasi iure fugit harum id odio?   Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati magni tenetur delectus fuga corporis quibusdam natus omnis assumenda eius excepturi, et ad voluptates animi quasi iure fugit harum id odio?   Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati magni tenetur delectus fuga corporis quibusdam natus omnis assumenda eius excepturi, et ad voluptates animi quasi iure fugit harum id odio? 
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati magni tenetur delectus fuga corporis quibusdam natus omnis assumenda eius excepturi, et ad voluptates animi quasi iure fugit harum id odio?   Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati magni tenetur delectus fuga corporis quibusdam natus omnis assumenda eius excepturi, et ad voluptates animi quasi iure fugit harum id odio?   Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati magni tenetur delectus fuga corporis quibusdam natus omnis assumenda eius excepturi, et ad voluptates animi quasi iure fugit harum id odio?   Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati magni tenetur delectus fuga corporis quibusdam natus omnis assumenda eius excepturi, et ad voluptates animi quasi iure fugit harum id odio?   Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati magni tenetur delectus fuga corporis quibusdam natus omnis assumenda eius excepturi, et ad voluptates animi quasi iure fugit harum id odio?   Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati magni tenetur delectus fuga corporis quibusdam natus omnis assumenda eius excepturi, et ad voluptates animi quasi iure fugit harum id odio?   Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati magni tenetur delectus fuga corporis quibusdam natus omnis assumenda eius excepturi, et ad voluptates animi quasi iure fugit harum id odio?   Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati magni tenetur delectus fuga corporis quibusdam natus omnis assumenda eius excepturi, et ad voluptates animi quasi iure fugit harum id odio? 
      
      
       </Link>
    </div>
  );
}
